name: Outrage Porn
favicon: null
layout_spectrum: 0.14663045667111874
typography_spectrum: 0.6982611974235624
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.622094325022772
  lightness: 0.3949537363369018
  saturation: 0.9977170240599662
  rhythmicContrast: 0.8412537225522101
purpose: []
